tabPanel("Visualisation",
  fluidRow(
    column(3,wellPanel(
      conditionalPanel('input.difftype=="Diffgene"',
        radioButtons(inputId='diff_cp',label='Comparison Group',choices=comparelist,selected=comparelist[1]),
        helpText('Choose one group'),
        numericInput(inputId='diff_fc',label='Fold Change',value=1,width=200),
        numericInput(inputId='diff_p',label='P-value',value=0.05,min=0,max=1,step=0.01,width=200),
        numericInput(inputId='diff_q',label='Padj value',value=0.05,min=0,max=1,step=0.01,width=200),
        actionButton('diff_button','Show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatedly.'),
        downloadButton("diffgene_download",label="Download")),

      conditionalPanel('input.difftype=="Volcano"',
        radioButtons(inputId='volcano_cp',label='Comparison Group',choices=comparelist,selected=comparelist[1]),
        helpText('Choose one group'),
        numericInput(inputId='volcano_fc',label='Fold Change',value=1,width=200),
        numericInput(inputId='volcano_p',label='P-value',value=0.05,min=0,max=1,step=0.01,width=200),
        numericInput(inputId='volcano_q',label='Padj value',value=0.05,min=0,max=1,step=0.01,width=200),
        actionButton('volcano_button','Show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatedly.'),
        downloadButton("volcano_download",label="Download")),

      conditionalPanel('input.difftype=="Heatmap"',
        selectizeInput(inputId="heatmap_cps",label="Comparison Group",choices=comparelist,selected=comparelist,multiple=TRUE),
        helpText('Select group(s) to include in heatmap analysis.'),
        helpText('For each group choose:'),
        textInput(inputId='heatmap_fcs',label='Fold Change',value=paste(rep(1,length(comparelist)),collapse=" "),width=200),
        textInput(inputId='heatmap_ps',label='P-value',value=paste(rep(0.05,length(comparelist)),collapse=" "),width=200),
        textInput(inputId='heatmap_qs',label='Padj value',value=paste(rep(0.05,length(comparelist)),collapse=" "),width=200),
        helpText('Please separate values by a space.'),
        selectizeInput(inputId="heatmap_group",label="Display group label",choices=c('TRUE','FALSE'),selected='FALSE',multiple=FALSE,width=200),
        helpText('Label sample groupings on heatmap.'),
        selectizeInput(inputId="heatmap_scale",label="Heatmap scale",choices=c('Column','Row'),selected='Row',multiple=FALSE,width=200),
        helpText('Determine if the heatmap is scaled by rows or columns.'),
        selectizeInput(inputId="heatmap_cluster",label="Display cluster tree",choices=c('Row','Column','Both'),selected='Both',multiple=FALSE,width=200),
        selectizeInput(inputId="heatmap_showname",label="Display gene names",choices=c('TRUE','FALSE'),selected='FALSE',multiple=FALSE,width=200),
        helpText('Select "True" to show gene names in the heatmap, otherwise select "False."'),
        selectizeInput(inputId="heatmap_legend",label="Display Legend",choices=c('TRUE','FALSE'),selected='TRUE',multiple=FALSE,width=200),
        helpText('Select "True" to include a legend with the heatmap, otherwise select "False."'),
        numericInput(inputId='heatmap_fontsize_row',label='Heatmap row fontsize',value=8,width=200),
        helpText('Select a font size for the rows.'),
        numericInput(inputId='heatmap_fontsize_col',label='Heatmap column fontsize',value=6,width=200),
        helpText('Select a font size for the columns.'),
        textInput(inputId='heatmap_col',label='Heatmap color',value='red white blue',width=200),
        helpText('Input color choices for the heatmap, and separate colors with a space.'),
        helpText('Example: Red White Green'),
        actionButton('heatmap_button','Show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatedly.'),
        downloadButton("heatmap_download_pdf",label="PDF Format"),br(),
        br(),
        downloadButton("heatmap_download_txt",label="TXT Format")),

      conditionalPanel('input.difftype=="Venn"',
        selectizeInput(inputId="venn_cps",label="Comparison Group",choices=comparelist,selected=comparelist,multiple=TRUE),
        helpText('Select group(s) to include in venn analysis.'),
        helpText('For each group choose:'),
        textInput(inputId='venn_fcs',label='Fold Change',value=paste(rep(1,length(comparelist)),collapse=" "),width=200),
        textInput(inputId='venn_ps',label='P-value',value=paste(rep(0.05,length(comparelist)),collapse=" "),width=200),
        textInput(inputId='venn_qs',label='Padj value',value=paste(rep(0.05,length(comparelist)),collapse=" "),width=200),
        textInput(inputId='venn_col_fill',label='Fill Color',value=paste(rainbow(length(comparelist)),collapse=" "),width=200),
        helpText('Color of circles in Venn.'),
        textInput(inputId='venn_col_cat',label='Label Font color',value=paste(rainbow(length(comparelist)),collapse=" "),width=200),
        helpText('Color of labels in Venn.'),
        textInput(inputId='venn_cex_cat',label='Label Font Size',value=paste(rep(2,length(comparelist)),collapse=" "),width=200),
        helpText('Front size of labels in Venn.'),
        textInput(inputId='venn_dist_cat',label='Label Position',value=paste(rep(0.05,length(comparelist)),collapse=" "),width=200),
        helpText('Distance between label and corresponding circle.'),
        textInput(inputId='venn_alpha',label='Fill Transparency',value=paste(rep(0.5,length(comparelist)),collapse=" "),width=200),
        helpText('Transparency of circles in Venn.'),
        helpText('Please separate values by a space.'),
        actionButton('venn_button','show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatedly.'),
        downloadButton("venn_download",label="Download")))),

    mainPanel(
      tabsetPanel(id='difftype',
        tabPanel(title="Diffgene",br(),dataTableOutput("diffgene_table")),
        tabPanel(title="Volcano",br(),plotOutput("volcano_plot",width=600,height=600)),
        tabPanel(title="Heatmap",br(),plotOutput("heatmap_plot",width=600,height=600)),
        tabPanel(title="Venn",br(),plotOutput("venn_plot",width=600,height=600))))))
