tabPanel("GO Enrichment",
  fluidRow(
    column(3,wellPanel(
      conditionalPanel('input.gotype=="GO enrichment"',
        radioButtons(inputId='go_cp',label='Comparison Group',choices=comparelist,selected=comparelist[1]),
        helpText('Choose one of these compares '),
        numericInput(inputId='go_fc',label='Fold Change',value=1,width=200),
        numericInput(inputId='go_p',label='P-value',value=0.05,min=0,max=1,step=0.01,width=200),
        numericInput(inputId='go_q',label='Padj value',value=0.05,min=0,max=1,step=0.01,width=200),
        selectizeInput(inputId='go_enrich_type',label='GO bar type',choices=c('BP','CC','MF','ALL'),selected='ALL',multiple=FALSE,width=200),
        helpText('GO types, including cellular component, biological process, and molecular function'),
        numericInput(inputId='go_enrich_p',label='GO enrich p-value',value=1,min=0,max=1,step=0.01,width=200),
        helpText('Pvalue threshold for significant enrichment.'),
        numericInput(inputId='go_enrich_q',label='GO enrich padj',value=1,min=0,max=1,step=0.01,width=200),
        helpText('Padj threshold for significant enrichment.'),
        actionButton('go_enrich_button','Show',icon('refresh'),width = 118),br(),
        helpText('It takes a long time to Enrichment analysis, Please wait for a moment, do not click repeatedly.'),
        downloadButton("go_enrich_download",label="Download")),

      conditionalPanel('input.gotype=="GO bar"',
        selectizeInput(inputId='go_bar_type',label='GO bar type',choices=c('BP','CC','MF','ALL'),selected='ALL',multiple=FALSE,width=200),
        helpText('GO types, including cellular component, biological process, and molecular function'),
        numericInput(inputId='go_bar_number',label='GO bar number',value=10,width=200),
        helpText('GO Enrichment Bar Chart of DEGs.If term numbers less than the default,it will show anomalie.When this happend,please adjust the default'),
        actionButton('go_bar_button','Show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatedly.'),
        downloadButton("go_bar_download",label="Download")),

      conditionalPanel('input.gotype=="GO dot"',
        selectizeInput(inputId='go_dot_type',label='GO dot type',choices=c('BP','CC','MF','ALL'),selected='ALL',multiple=FALSE,width=200),
        helpText('GO types, including cellular component, biological process, and molecular function'),
        numericInput(inputId='go_dot_number',label='GO dot number',value=10,width=200),
        helpText('GO enrichment scatter plot of DEGs'),
        actionButton('go_dot_button','Show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatly'),
        downloadButton("go_dot_download",label="Download")),

      conditionalPanel('input.gotype=="GO dag"',
        selectizeInput(inputId='go_dag_type',label='GO dag type',choices=c('BP','CC','MF'),selected='BP',multiple=FALSE,width=200),
        helpText('GO types, including cellular component, biological process, and molecular function'),
        numericInput(inputId='go_dag_number',label='GO dag number',value=10,width=200),
        helpText('GO Enrichment DAG Figure,If term numbers less than the default,it will show anomalie.When this happend,please adjust the default'),
        actionButton('go_dag_button','Show',icon('refresh'),width = 118),br(),
        helpText('Please wait for a moment, do not click repeatly'),
         helpText('If the picture is not fully displayed, please download and view it.'),
        downloadButton("go_dag_download",label="Download")))),

    mainPanel(
      tabsetPanel(id='gotype',
        tabPanel(title="GO enrichment",br(),dataTableOutput('go_enrich')),
        tabPanel(title="GO bar",br(),plotOutput("go_bar",width=600,height=480)),
        tabPanel(title="GO dot",br(),plotOutput("go_dot",width=600,height=480)),
        tabPanel(title="GO dag",br(),plotOutput("go_dag",width=400,height=320))
       ))))
