if (!require("shiny")) install.packages("shiny")
library(shiny)
if (!require("shinyjs")) install.packages("shinyjs")
library(shinyjs)
if (!require("shinyBS")) install.packages("shinyBS")
library(shinyBS)
if (!require("shinyFiles")) install.packages("shinyFiles")
library(shinyFiles)
if (!require("shinyWidgets")) install.packages("shinyWidgets")
library(shinyWidgets)
if (!require("shinybusy")) install.packages("shinybusy")
library(shinybusy)
if (!require("shinyalert")) install.packages("shinyalert")
library(shinybusy)
if (!require("DT")) install.packages("DT")
library(DT)
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)
if (!require("Biostrings")) install.packages("Biostrings")
library(Biostrings)


